steps:

- id: 'execute-static-analysis' 
  name: maven:3-eclipse-temurin-17-alpine
  entrypoint: mvn
  args: ['verify', 'sonar:sonar', '-Pcoverage', '-Dsonar.login=$$TOKEN', '-Dsonar.host.url=$$URL', '-Dsonar.organization=$$ORG', '-Dsonar.projectKey=$$PROJECT']
  dir: 'cirene-svc'  
  secretEnv: ['TOKEN', 'PROJECT', 'ORG', 'URL']

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/SONAR_TOKEN/versions/1
    env: TOKEN
  - versionName: projects/$PROJECT_ID/secrets/SONAR_PROJECT/versions/1
    env: PROJECT
  - versionName: projects/$PROJECT_ID/secrets/SONAR_ORG/versions/1
    env: ORG
  - versionName: projects/$PROJECT_ID/secrets/SONAR_URL/versions/1
    env: URL
 