steps:

- name: 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
  id: Sonar Scanner
  entrypoint: /bin/bash
  args:
    - '-c'
    - |
      sonar-scanner \
        -Dsonar.host.url=$$URL \
        -Dsonar.login=$$TOKEN \
        -Dsonar.projectKey=$$PROJECT \
        -Dsonar.organization=$$ORG \
        -Dsonar.sources=cirene-svc/
  secretEnv: ['TOKEN', 'PROJECT', 'ORG', 'URL']

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/SONAR_TOKEN/versions/1
    env: TOKEN
  - versionName: projects/$PROJECT_ID/secrets/SONAR_PROJECT/versions/1
    env: PROJECT
  - versionName: projects/$PROJECT_ID/secrets/SONAR_ORG/versions/1
    env: ORG
  - versionName: projects/$PROJECT_ID/secrets/SONAR_URL/versions/1
    env: URL
 