steps:

- name: maven:3-eclipse-temurin-17-alpine
  entrypoint: mvn
  args: ["test"]
  dir: 'cirene-svc'
  allowExitCodes: [1]

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$LOCATION-docker.pkg.dev/$PROJECT_ID/cirene-svc/cirene-svc-v4:$COMMIT_SHA', '--build-arg', 'ENABLE_RATING=true', '--build-arg', 'ENABLE_INFO=true', '.']
  dir: 'cirene-svc'

images:
- '$LOCATION-docker.pkg.dev/$PROJECT_ID/cirene-svc/cirene-svc-v4:$COMMIT_SHA'

artifacts:
  objects:
    location: 'gs://devops-demo-prj-tfstate/$PROJECT_ID/surefire-reports'
    paths:
      - 'cirene-svc/target/surefire-reports/*'
 