steps:

#- name: maven:3-eclipse-temurin-17-alpine
#  entrypoint: mvn
#  args: ["test"]
#  dir: 'cirene-svc'
#  allowExitCodes: [1]

#- name: 'gcr.io/k8s-skaffold/skaffold'
#  entrypoint: 'sh'
#  args:
#  - -xe
#  - -c
#  - |
#    # Build and push images
#    skaffold build --file-output=/workspace/artifacts.json \
#                   --default-repo=$LOCATION-docker.pkg.dev/$PROJECT_ID/cirene-svc \
#                   --push=true    

#- name: 'google/cloud-sdk:latest'
#  entrypoint: 'sh'
#  args:
#  - -xe
#  - -c
#  - |
#    gcloud config set deploy/region $LOCATION
#    gcloud deploy releases create rel-${SHORT_SHA} \
#                        --delivery-pipeline devops-demo-cd-pipeline \
#                        --description "$(git log -1  --pretty='%s')" \
#                        --build-artifacts /workspace/artifacts.json \
#                        --annotations "commit_ui=https://github.com/cssantos0/devops-sample-app-demo/commit/$COMMIT_SHA" 

- id: 'func-tests-get-svc-ip'
  name: 'google/cloud-sdk:latest'
  entrypoint: 'sh'
  dir: 'tests/functional-tests'
  args:
  - -xe
  - -c
  - |
    #gcloud components install kubectl
    apt-get install kubectl
    gcloud container clusters get-credentials gke-staging-cluster --zone ${_GCP_ZONE} --project $PROJECT_ID
    kubectl -n demo-app-staging get svc cirene-svc --output jsonpath='{.status.loadBalancer.ingress[0].ip}' > /workspace/cirenehost.txt

- id: 'func-tests-show-ip'
  name: ubuntu
  entrypoint: bash
  dir: 'tests/functional-tests'
  args:
    - -c
    - |      
      echo "HOST: " $(cat /workspace/cirenehost.txt)  
      docker build -t $LOCATION-docker.pkg.dev/$PROJECT_ID/functional-tests/functional-tests --build-arg CIRENE_URL_HOST=$(cat /workspace/cirenehost.txt)
      docker run $LOCATION-docker.pkg.dev/$PROJECT_ID/functional-tests/functional-tests
  waitFor: ['func-tests-get-svc-ip']

- id: 'func-tests-build'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$LOCATION-docker.pkg.dev/$PROJECT_ID/functional-tests/functional-tests', '--build-arg', 'CIRENE_URL_HOST="$(cat /workspace/cirenehost.txt)"', '.']
  dir: 'tests/functional-tests'
  waitFor: ['func-tests-get-svc-ip']

- id: 'func-tests-push'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', '$LOCATION-docker.pkg.dev/$PROJECT_ID/functional-tests/functional-tests']
  dir: 'tests/functional-tests'
  waitFor: ['func-tests-build']

- id: 'func-tests-run'
  name: 'gcr.io/cloud-builders/docker'
  args: ['run', '$LOCATION-docker.pkg.dev/$PROJECT_ID/functional-tests/functional-tests']
  dir: 'tests/functional-tests'
  waitFor: ['func-tests-push']

#artifacts:
#  objects:
#    location: 'gs://devops-demo-prj-cloudbuild-artifacts/$PROJECT_ID/$BUILD_ID'
#    paths:
#      - '/workspace/cirene-svc/target/surefire-reports/*'
#      - '/workspace/artifacts.json'

options:
  machineType: E2_HIGHCPU_8

timeout: 3600s