apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: cirene-svc
build:
  tagPolicy:
    sha256: {}    
  artifacts:
  - image: cirene-svc-v4
    context: cirene-svc
    docker:
      dockerfile: Dockerfile
      buildArgs:
        ENABLE_INFO: 'true'
        ENABLE_RATING: 'true'
test:
  - image: cirene-svc-v4 
    context: cirene-svc
    custom:
      - command: ./execute-code-analysis.sh
        timeoutSeconds: 120
        dependencies:
          paths:
          -  "execute-code-analysis.sh"         
deploy:
  kustomize:
    paths: 
    - deploy/kustomize/overlays/cirene-svc/development
portForward:
- resourceType: service
  resourceName: cirene-svc
  namespace: demo-app
  port: 4000    
  
profiles: 

  - name: sandbox-profile
    activation:
      - kubeContext: sandbox
    build:
      googleCloudBuild: {}
      tagPolicy:
        sha256: {}   
      artifacts:
      - image: us-central1-docker.pkg.dev/devops-demo-prj/cirene-svc/cirene-svc-v4
        context: cirene-svc
        docker:
          dockerfile: Dockerfile   
          buildArgs:
            ENABLE_INFO: 'true'  
            ENABLE_RATING: 'true'
    deploy:
      kustomize:
        paths: 
        - deploy/kustomize/overlays/cirene-svc/sandbox
    portForward:
    - resourceType: service
      resourceName: cirene-svc
      namespace: demo-app-sandbox
      port: 4000

  - name: staging-profile
    activation:
      - kubeContext: staging
    build:
      googleCloudBuild: {}
      tagPolicy:
        sha256: {}   
      artifacts:
      - image: us-central1-docker.pkg.dev/devops-demo-prj/cirene-svc/cirene-svc-v4
        context: cirene-svc
        docker:
          dockerfile: Dockerfile   
          buildArgs:
            ENABLE_INFO: 'true'  
            ENABLE_RATING: 'true'
    deploy:
      kustomize:
        paths: 
        - deploy/kustomize/overlays/cirene-svc/staging
    portForward:
    - resourceType: service
      resourceName: cirene-svc
      namespace: demo-app-staging
      port: 4000

  - name: production-profile
    activation:
      - kubeContext: production
    deploy:
      kustomize:
        paths: 
        - deploy/kustomize/overlays/cirene-svc/production
    portForward:
    - resourceType: service
      resourceName: cirene-svc
      namespace: demo-app-prod
      port: 4000   
     