apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: cirene-svc
build:
  tagPolicy:
    sha256: {}      
  local:
    push: false
  artifacts:
  - image: cirene-svc-v4
    docker:
      dockerfile: Dockerfile
      buildArgs:
        ENABLE_INFO: 'true'
        ENABLE_RATING: 'true'
#test:
  #- image: cirene-svc-v4
  #  custom:
  #    - command: mvn clean test
  #      timeoutSeconds: 60
  #- image: cirene-svc-v4
  #  custom:
  #    - command: ./execute-code-analysis.sh
  #      timeoutSeconds: 60
  #      dependencies:
  #        paths:
  #        -  "execute-code-analysis.sh"      
deploy:
  kustomize:
    paths: 
    - ../deploy/kustomize/overlays/cirene-svc/development
portForward:
- resourceType: service
  resourceName: cirene-svc
  namespace: demo-app
  port: 4000
  
profiles:
  - name: production-profile
    activation:
      - kubeContext: production
    build:
      googleCloudBuild: {}
      tagPolicy:
        sha256: {}   
      artifacts:
      - image: us-central1-docker.pkg.dev/devops-demo-prj/cirene-svc/cirene-svc-v4
        docker:
          dockerfile: Dockerfile   
          buildArgs:
            ENABLE_INFO: 'true'  
            ENABLE_RATING: 'true'
    deploy:
      kustomize:
        paths: 
        - ../deploy/kustomize/overlays/cirene-svc/production
    portForward:
    - resourceType: service
      resourceName: cirene-svc
      namespace: demo-app-prod
      port: 4000    
  - name: staging-profile
    activation:
      - kubeContext: staging
    build:
      googleCloudBuild: {}
      tagPolicy:
        sha256: {}   
      artifacts:
      - image: us-central1-docker.pkg.dev/devops-demo-prj/cirene-svc/cirene-svc-v4
        docker:
          dockerfile: Dockerfile   
          buildArgs:
            ENABLE_INFO: 'true'  
            ENABLE_RATING: 'true'
    deploy:
      kustomize:
        paths: 
        - ../deploy/kustomize/overlays/cirene-svc/staging
    portForward:
    - resourceType: service
      resourceName: cirene-svc
      namespace: demo-app-staging
      port: 4000        
