apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-app
commonLabels:
  env: dev
resources:
  - ../../../base
  - ../../../base/cirene-svc
patches:
  - target:      
      kind: Deployment
      name: cirene-svc-v4
    path: deployment-v4-patch.yaml         
